### ISSUE TITLE
Force Production parameter does not seem to honor current state of user

### ISSUE THREAD

**Issue by nsepetys** [looker-open-source/sdk-codegen#1013]
Hi,

We are using the Python SDK (API version 4.0 and SDK version 21.6.0) and are noticing (and have been since we adopted usage of the Looker SDK) that this [parameter](https://github.com/looker-open-source/sdk-codegen/blob/6f9c8b0065acebe0304b0db121ac0ccdfb1466d4/python/looker_sdk/sdk/api40/methods.py#L7142) (`force_production`) does not seem to behave as expected. We expect if `force_production = False` if the user is in development mode any Looks, Dashboards, or queries will be ran against the development mode code. This is not what we are observing. It appears production code is always used regardless of the `force_production` value. We have confirmed by comparing the SQL being ran via the SDK on the Looker Queries page.

Is anyone else able to replicate this?

- Noah

**Comment by jkaster** [comment]
Hi, Noah. You mentioned this hasn't been working since you adopted the Looker SDK. What were you using to successfully make this call before? And do you have the failing code snippet you can share?

**Comment by nsepetys** [comment]
@jkaster - To be honest, I don't know if we ever got it working using `http`. I'll have to get back to you on the snippet. Code is not exactly in a place that I can snip a piece out and have it work. Let me see if I can get you something though.

**Comment by jkaster** [comment]
Thanks!

**Comment by nsepetys** [comment]
Let me know if you can't replicate.
```python
import sys
import textwrap

import looker_sdk
from looker_sdk import models

sdk = looker_sdk.init40("././looker.ini")


def run_dev_look(look_id, result_format, image_width, image_height):
    """ Gets Look query and re-runs it using dev mode."""

    look = sdk.look(look_id)
    q = look.query
    request = models.WriteQuery(
            model=q.model,
            view=q.view,
            fields=q.fields,
            pivots=q.pivots,
            fill_fields=q.fill_fields,
            filter_config=q.filter_config,
            filter_expression=q.filter_expression,
            filters=q.filters,
            sorts=q.sorts,
            limit=q.limit,
            column_limit=q.column_limit,
            total=q.total,
            row_total=q.row_total,
            subtotals=q.subtotals,
            dynamic_fields=q.dynamic_fields,
            query_timezone=q.query_timezone,
            vis_config=q.vis_config,
        )
    try:
        query_return = sdk.run_inline_query(
            result_format=result_format,
            body=request,
            cache=False,
            image_width=image_width,
            image_height=image_height,
            force_production=False  # We expect to get Look ran on dev mode. ini supplies details for user in dev mode
        )
    except Exception:
        raise Exception("Error running query")

    return query_return

def main():
    look_title = sys.argv[1] if len(sys.argv) > 1 else ""
    image_width = int(sys.argv[2]) if len(sys.argv) > 2 else 545
    image_height = int(sys.argv[3]) if len(sys.argv) > 3 else 842
    image_format = sys.argv[4] if len(sys.argv) > 4 else "png"

    if not look_title:
        raise Exception(
            textwrap.dedent(
                """
                Please provide: <lookTitle> [<img_width>] [<img_height>] [<img_format>]
                    img_width defaults to 545
                    img_height defaults to 842
                    img_format defaults to 'png'"""
            )
        )

    look = get_look(look_title)
    download_look(look, image_format, image_width, image_height)


def get_look(title: str) -> models.Look:
    title = title.lower()
    look = next(iter(sdk.search_looks(title=title)), None)
    if not look:
        raise Exception(f"look '{title}' was not found")
    return look


def download_look(look: models.Look, result_format: str, width: int, height: int):
    """Download specified look as png/jpg"""
    id = int(look.id)

    result = run_dev_look(id, result_format, width, height)

    filename = f"{look.title}.{result_format}"
    with open(filename, "wb") as f:
        f.write(result)
    print(f"Look saved to '{filename}'")


main()
```

**Comment by jkaster** [comment]
Thanks again. We'll look into this.

**Comment by jkaster** [comment]
It looks like this is a documentation error. `force_production` is ignored in this endpoint and several others where it is defined.

**Comment by jkaster** [comment]
FWIW, this bug has existed since 2018. Thanks for bringing it to our attention.

**Comment by jkaster** [comment]
Ok, I got some more information from the query team. We'll be updating the parameter description to say something along the lines of:

> Note that this flag being false does not guarantee development models will be used.

Setting the value to `true` is what's supposed to ensure production is used.

**Comment by nsepetys** [comment]
> Ok, I got some more information from the query team. We'll be updating the parameter description to say something along the lines of:
> 
> > Note that this flag being false does not guarantee development models will be used.
> 
> Setting the value to `true` is what's supposed to ensure production is used.

Is there an answer from the query team of how we determine what the expected behavior is when setting it to `false`?

**Comment by jkaster** [comment]
At this point, there is no expected behavior when it is set to `false`. I encourage you to create a Looker feature request for this.

**Comment by nsepetys** [comment]
Thanks for investigating this @jkaster . I have put the feature request in here- https://portal.feedback.us.pendo.io/app/#/case/174866?currentProductId=53ee6715-9dcb-471f-bd41-7846ac4d9e41&section=requests .

**Comment by jkaster** [comment]
Thank you!
