### ISSUE TITLE
Python: verify api_version defaults to 3.1

### ISSUE THREAD

**Issue by jkaster** [looker-open-source/sdk-codegen#102]
If the api version isn't specified in the configuration, it should default to our active supported version, which is currently 3.1

**Comment by josephaxisa** [comment]
This is already the case in the Python SDK. Here's the test for it: 
https://github.com/looker-open-source/sdk-codegen/blob/ce1d0c0db17d48d59eccaa870f2899d184cff69a/python/tests/rtl/test_api_settings.py#L99-L108
If that's ok we can close this issue.

**Comment by jkaster** [comment]
A nice test already exists to verify the API version defaults to 3.1
