### ISSUE TITLE
[Typescript SDK] types that should be generics instead hardcode string

### ISSUE THREAD

**Issue by belzile** [looker-open-source/sdk-codegen#1082]
The generated TS SDK defines its types like this:

```ts
run_inline_query(request: IRequestRunInlineQuery, options?: Partial<ITransportSettings>): Promise<SDKResponse<string, IError | IValidationError>>;
```

What's wrong with this? The return of inline query is rarely a string. It is an object determined by the fields requested in the `request` option. Instead, the type of `run_inline_query` should contain a generic as follow:

```ts
run_inline_query<T>(request: IRequestRunInlineQuery, options?: Partial<ITransportSettings>): Promise<SDKResponse<T, IError | IValidationError>>;
```

It's not the only function with this issue.

**Comment by jkaster** [comment]
Hi. The code generator declares the method signature based on the Looker API specification. The specification for the `run_inline_query` response types is available at https://developers.looker.com/api/explorer/4.0/methods/Query/run_inline_query in the last section called  *Original Schema*. It is collapsed by default but can be expanded by clicking on it.

```json
  "responses": {
    "200": {
      "description": "Query Result",
      "content": {
        "text": {
          "schema": {
            "type": "string"
          }
        },
        "application/json": {
          "schema": {
            "type": "string"
          }
        },
        "image/png": {
          "schema": {
            "type": "string"
          }
        },
        "image/jpeg": {
          "schema": {
            "type": "string"
          }
        }
      }
    },
```

I omitted the `4XX` response types from this snippet but they're available on the Developer Portal. These response types are what is used to generate the return signature from the method.

Note that the `T` in the proposed type signature is not consumed by the arguments, only the return value. 

That means there is no hope of type inference; you have to supply the generic as a hint for the return type that is totally divorced from the actual runtime inputs. Casting the result result with `as` amounts to the same thing.

If `T` could meaningfully be mapped to the response represented by the `response_format` parameter, it would be useful to create a union type of responses for the Promise's return, but this information isn't available from the specification and I haven't seen that kind of association available in OpenAPI.

The current SDK, as generated, provides all `run_inline_query` responses correctly. If you have scenarios where it doesn't work, please let us know.

**Comment by fwojciec** [comment]
@jkaster The problem here seems to be that the SDK returns a parsed JSON (so effectively an object) value rather than a stringified JSON value for the `json` result format as the API typings above suggest.  The types would work fine if not for the fact that the SDK seems to run `JSON.parse` on the result for some reason.  I does feel very awkward that I have to cast the type from `string` to an `Record` of some sort just to be able to interact with the response value.

**Comment by jkaster** [comment]
The limitation is with run_inline_query. It has no schema for the `application/json` payload at the API specification level (the structure is dynamically determined and returned is based on the query). The SDK transport recognizes the content type and parses application/json payloads as the return value. There is no generic SDK-level solution for explicitly typing the response from an arbitrary query request, so casting to a general purpose type is the only solution that comes to mind. If you look at the returns from endpoints with known structure responses (like search_dashboards) that does provide the type information you'd like to have. For dynamic queries, the API can't specify a specific type. How are you planning on consuming the `application/json` payload differently than starting with parsing it?

**Comment by fwojciec** [comment]
Thanks for the additional explanation. Yeah, in 99% of cases I would just parse the stringified JSON as soon as it's returned. I see the reasoning behind the current implementation.

That said, my preference would still be for the result to be a stringified JSON value. This would be consistent with the typing of the method.  It would also be consistent with how the method behaves in case of other `result_format` values (for example `csv`).  Finally, that would be consistent with how other language SDKs behave - at least the Go SDK which just returns a string and leaves it to the user to parse.

I appreciate that not everyone shares my preference in this regard. :)

**Comment by jkaster** [comment]
Thanks for your feedback. Parsing it when it the payload is json and returning that value is what makes supporting all the other specifically typed generics feasible. We will avoid adding boilerplate code to the hundreds of other functions that get generated by processing the payload at the transport level.

The Go SDK doesn't actually follow our best practices for our language SDKs yet! We try to provide the response type based on what's provided in the actual payload. `application/json` is a string representation of JSON, so if it can be parsed as JSON. that's what our runtime returns. Just like image files are not converted to UTF-8 but provided as byte streams or byte arrays.
