### ISSUE TITLE
Exponential back-off retry in Python SDK

### ISSUE THREAD

**Issue by ad-m-ss** [looker-open-source/sdk-codegen#1089]
Hello,

We use Python SDK to integrate with Looker. Unfortunately, we notice some random failures on Looker side. 

```
File "/app/data_sources/connectors/bi_tools/looker.py", line 107, in get_users
return self.sdk.all_users()
File "/usr/local/lib/python3.10/site-packages/looker_sdk/sdk/api31/methods.py", line 9085, in all_users
self.get(
File "/usr/local/lib/python3.10/site-packages/looker_sdk/rtl/api_methods.py", line 143, in get
return self._return(response, structure)
File "/usr/local/lib/python3.10/site-packages/looker_sdk/rtl/api_methods.py", line 87, in _return
raise error.SDKError(response.value.decode(encoding=encoding))
looker_sdk.error.SDKError: <html>
<head><title>502 Bad Gateway</title></head>
<body>
<center><h1>502 Bad Gateway</h1></center>
<hr><center>nginx</center>
</body>
</html>
```

What do you think about adding exponential back-off in Python SDK? This can be of value at least for a read operation.

Kind regards

**Comment by ad-m-ss** [comment]
API Improvement Proposals of Google for "Client-side retry" defines that the client library should provide automatic, client-side retry logic. See details at https://google.aip.dev/client-libraries/4221 

Could we adhere to Google standard?

**Comment by jkaster** [comment]
Hi. Thanks for the suggestion. The 502 gateway response sounds like an infrastructure issue that needs a support ticket. As for the client-side retry, we don't have plans to implement that directly in the SDKs at this time. 

We do have work planned to be done before the end of the year to provide all API error response information in the exception that's thrown in the SDKs (some information in some of the SDKs is currently lost in the `catch` block) so all information to make the appropriate decision for a general-purpose retry/delay loop would be feasible at that point. 

It is possible to implement your own retry handler today as a wrapper around the SDK calls.
