### ISSUE TITLE
serialize missing 1 required keyword-only argument: 'converter'

### ISSUE THREAD

**Issue by moveingsun** [looker-open-source/sdk-codegen#1171]
hi there, so recently I have updated the python package looker-sdk from 22.2.0 to 22.10.0. And we hit an exception where stacktrace is 
```
lib/python3.9/site-packages/looker_sdk/rtl/api_methods.py", line 150, in _get_serialized
    serialized = self.serialize(api_model=body)  # type: ignore

TypeError: serialize() missing 1 required keyword-only argument: 'converter'
```
And this is how we initiate the client with Looker31SDK
```
from looker_sdk.sdk.api31 import methods as methods31
from looker_sdk.rtl import auth_session, serialize, transport
client = methods31.Looker31SDK(
            auth=auth_session.AuthSession(settings, transport, serialize.deserialize31, "3.1"),
            deserialize=serialize.deserialize31,
            serialize=serialize.serialize,
            transport=transport,
            api_version="3.1",
        )
```
The issue is that when triggering the api get method and serilize body at [here](https://github.com/looker-open-source/sdk-codegen/blob/b1650a1a8a56c52a7a06ca5c9cef02300af7289e/python/looker_sdk/rtl/api_methods.py#L150), it only pass in one parameter `api_model`. And based on this [change](https://github.com/looker-open-source/sdk-codegen/pull/1015/files#diff-e9e1173a6a3a1ab95641aad599a60858bfaef456109b4ce2958ac9782005f55aR78-R80), the serialize is now requiring two parameter `api_model` and `converter`. so do i miss something here? or this is actually a bug.

**Comment by joeldodge79** [comment]
sorry, yeah now you need to pass in `serialize=serialize.serialize31` (see [here](https://github.com/looker-open-source/sdk-codegen/pull/1015/files#diff-af3c436cd79cbb8cb66d7924ecd7554577078e69d6c41af2823e6a7cf09e8fddR65))
