### ISSUE TITLE
Go sdk: LoginUser access token

### ISSUE THREAD

**Issue by sumairz** [looker-open-source/sdk-codegen#1196]
Hello, I want some clarity on how to use the access token I get from `LoginUser` method. I am trying to sudo user's who doesn't have client id and client secret.

I want to use `AllDashboards` and pass the access token as header but It seems like there is no way to do it or am I missing something. If someone can provide a clear example.

**Comment by mgrzebyksc** [comment]
Wouldn't it be easier for you to simply initialize full SDK (which will manage the token lifecycle)?

e.g. `sdk := v4.NewLookerSDK(rtl.NewAuthSession(cfg))`

Then you can simply perform any looker api call without worrying about the token. Code generated in this package already has all of the logic for refreshing the token built in so you won't have to worry about it.

**Comment by jeremytchang** [comment]
There's no way to "sudo user's who doesn't have client id and client secret". The access token you get from the login endpoint is associated with the user's client id/secret. 

Seconding @mgrzebyksc. The Go SDK manages the fetching, setting, and refreshing of the access token as long as you provide the client id/secret either through environment variables, or looker.ini config file, or you pass in the settings/config struct.  Checkout our simple example here: https://github.com/looker-open-source/sdk-codegen/blob/main/go/example/main.go#L68

Closing this issue, however feel free to re-open if you have further questions.
