### ISSUE TITLE
Tests modules overwrites local tests 

### ISSUE THREAD

**Issue by teika-dave** [looker-open-source/sdk-codegen#1197]
When importing the python module looker_sdk, the `tests` module is also built, which overrides the local `tests` directory, which forces a directory rename, and thus a refactor of all testing code that uses it.

looker_sdk version is `22.18.0`, installed with pip

**Comment by antonio-antuan** [comment]
bump

**Comment by otosky** [comment]
@jeremytchang @christelilaka 

can #1416 be merged to address this?  this crops up for installs of Apache Airflow that pull in the google-related extras.
