### ISSUE TITLE
Typescript ISetting missing host_url field

### ISSUE THREAD

**Issue by taystack** [looker-open-source/sdk-codegen#1239]
|package|version|
|----|----|
|`typescript`|`4.9.4`|
|`@looker/sdk`|`22.20.1`|

I am trying to leverage the `ILooker40SDK.get_setting` API to get the `host_url` field.
- https://developers.looker.com/api/explorer/4.0/methods/Config/get_setting?s=host_url

Problem is the exported `ISetting` interface is missing the `host_url` field.

![Screen Shot 2023-01-25 at 3 55 34 PM](https://user-images.githubusercontent.com/2994672/214720555-9825b604-6ad8-42ec-927d-5a740b4071e9.png)

I can hack a workaround but it kinda smells:
```typescript
const setting = (await core40.ok(core40.get_setting())) as ISetting & { host_url: string }
```

**Comment by jkaster** [comment]
`ISetting` is generated from the Looker API specification. If it's missing a property, it's an SDK version mismatch. Make sure you're using a current SDK that has the property defined. https://developers.looker.com/api/explorer/4.0/types/Config/Setting is the latest spec, which shows `host_url` exists. It looks like this property got added in `23.0` https://developers.looker.com/api/explorer/23.0%204.0/types/Config/Setting
