### ISSUE TITLE
nodejs sdk send api key and api secret via query string, it should be send via body. 

### ISSUE THREAD

**Issue by yingbiao** [looker-open-source/sdk-codegen#126]
We noticed the nodejs SDK is sending api key and api secret via querystring. It should be send via body instead. 

https://github.com/looker-open-source/sdk-codegen/blob/2e1e8f8471fb0c9c4c8c981d6899658bd4abe0ec/typescript/looker/rtl/nodeSession.ts#L201

**Comment by elexisvenator** [comment]
Just to clarify the impact of this - 
With the api credentials in the querystring, we are seeing the secret being logged in our firewall logs, and server logs. Basically, anyone who looks at this request (MITM style) can see our auth credentials _without having to ssl decrypt the request_.

**Comment by jkaster** [comment]
Thanks for pointing this out. I missed that argument positional change in a refactor. It'll be fixed shortly.
