### ISSUE TITLE
Looker_SDK create_project not working-Python(404 Not Found)

### ISSUE THREAD

**Issue by deeksha01Q** [looker-open-source/sdk-codegen#1276]
Not able create project using looker sdk in python 

![image](https://user-images.githubusercontent.com/102579787/225586641-1d23795c-16fa-44a3-86c2-9defb6718a1d.png)

**Comment by jeremytchang** [comment]
Hey, it looks like you're getting a 404. It may be a permissions issue, or your SDK settings (like base looker url) aren't correct. https://help.looker.com/hc/en-us/articles/4420221305107-Why-do-I-see-a-404-in-Looker-Community-

**Comment by jeremytchang** [comment]
Closing, but feel free to reopen if your issue still permits.
