### ISSUE TITLE
node_modules (sdk-node) error with Typescript Angular

### ISSUE THREAD

**Issue by vinay-murkpudi** [looker-open-source/sdk-codegen#1305]
Hi Team,

I keep getting errors when I integrate  **@looker/sdk-node** versions with Angular and then start server.

took reference from Looker Github project:
https://github.com/looker-open-source/sdk-codegen/tree/fb19b8f45078aa4b6a7f91bf817c48418b19ffae/examples/typescript

sample live project with errors are attached in below:
https://stackblitz.com/edit/angular-od7a4u?file=package.json,src%2Fmain.ts

 --ERROR:-- in console 

```
./node_modules/@looker/sdk-node/lib/nodeSettings.js:7:33-46 - Error: Module not found: Error: Can't resolve 'fs' in 'C:\DDrive\Web\looker-test\node_modules\@looker\sdk-node\lib'
./node_modules/@looker/sdk-node/lib/nodeTransport.js:7:37-54 - Error: Module not found: Error: Can't resolve 'crypto' in 'C:\DDrive\Web\looker-test\node_modules\@looker\sdk-node\lib'
BREAKING CHANGE: webpack < 5 used to include polyfills for node.js core modules by default.
This is no longer the case. Verify if you need this module and configure a polyfill for it.
If you want to include a polyfill, you need to:
        - add a fallback 'resolve.fallback: { "crypto": require.resolve("crypto-browserify") }'
        - install 'crypto-browserify'
If you don't want to include a polyfill, you can use an empty module like this:
        resolve.fallback: { "crypto": false }
./node_modules/asn1/lib/ber/reader.js:3:13-30 - Error: Module not found: Error: Can't resolve 'assert' in 'C:\DDrive\Web\looker-test\node_modules\asn1\lib\ber'
```

**Comment by jkaster** [comment]
the `@looker/sdk-node` package is a server-side SDK package specifically for node servers. It will not work client-side with Angular or any browser app.

**Comment by jkaster** [comment]
The `@looker/sdk` package and `@looker/sdk-rtl` dependency are plain JS libraries that have no requirements other than the browser. Once an authentication token is retrieved for the API via either your own proxy to login to the Looker instance, or via an OAuth handshake, requests to the Looker API can be performed with any JS in the browser that can make CORS requests. We don't provide support for Angular, only our SDK.

Once the SDK is initialized with an authentication token, code like the following works in Angular or anything else:

```ts
// functional SDK syntax is recommended for minimizing browser payloads
let response = await sdk.ok(run_inline_query(sdk,
  {
    result_format: 'json',
    body: {
      model: 'thelook',
      view: 'order_items',
      total: false
    }
  }))
// monolithic SDK syntax can also be used for Node apps
let response = await sdk.ok(sdk.run_inline_query(
  {
    result_format: 'json',
    body: {
      model: 'thelook',
      view: 'order_items',
      total: false
    }
  }))
  ```
  
Please see https://developers.looker.com/api/getting-started?language=typescript for information about authenticating with the TypeScript SDK
