### ISSUE TITLE
copy_dashboard doesn't exist

### ISSUE THREAD

**Issue by acameronHEB** [looker-open-source/sdk-codegen#1325]
Hello,

copy_dashboard isn't an available function in Python LC objects although it's available in the API reference. https://developers.looker.com/api/explorer/4.0/methods/Dashboard/copy_dashboard?s=dashboard&sdk=py

Steps to reproduce:
         LC = looker_sdk.init40(LOOKER_CONFIG_PATH)
         LC.copy_dashboard()

ERROR:
         AttributeError: 'Looker40SDK' object has no attribute 'copy_dashboard'

**Comment by deanlooker** [comment]
It's likely that your version of the SDK is out of date. Please pull changes from this repository (`git@github.com:looker-open-source/sdk-codegen.git`) to ensure your version of the Looker Python SDK is up-to-date and then try this again.

**Comment by acameronHEB** [comment]
Cloning and installing worked. Thanks!
