### ISSUE TITLE
Unable to compile Java SDK

### ISSUE THREAD

**Issue by nworden** [looker-open-source/sdk-codegen#1328]
Hi!

I'm attempting to build the Java SDK in order to upgrade. I've added `'--skip-validate-spec',` to the `openapi-generator-cli` call, as recommended [here](https://github.com/looker-open-source/sdk-codegen/issues/978#issuecomment-1569135887) (after encountering the same validator error discussed there), but otherwise I'm using the code from this repo as-is.

With the validation skip, running `yarn legacy java` does produce Java files, but when I run `gradle jar` (from within `api/4.0/java`) I get many errors. The main problem(s) seems to be that
- There are five enums in the same parent class (`org.openapitools.client.model.Integration`) with the same name,
- That name is "String," and
- They have no values, so they're not valid enums.

The `LookmlModelExploreField` class also has a "String" enum with no values.

Any ideas about where I'm going wrong?

**Comment by jkaster** [comment]
Sorry for the difficulties. Our recommended solution is to use our Kotlin-generated SDK with Java. I don't anticipate having an opportunity in the near future to resolve any new issues with the `legacy` generation option. There are some [examples for Java](https://github.com/looker-open-source/sdk-codegen/tree/main/examples/java) that do this.
