### ISSUE TITLE
Typescript SDK: `run_inline_query` with `result_format='xlsx'` yields currupt data

### ISSUE THREAD

**Issue by rhighs** [looker-open-source/sdk-codegen#1334]
Trying to get looker query results as 'xlsx' data responds with corrupted binary data (starting with prefix PK as imposed by PKzip used in excel file format specification)

```ts
const { ok, value } = await lookerClient
            .run_inline_query({
              result_format: 'xlsx',
              body: '<some_query>'
            })

if (ok) {
  console.log(value)
}
```

```
PK��~ÚV���������������[Content_Types].xmlµSËnÂ0üÈ×*6ôPUCÇ©ô\{Xø%¯¡ð÷]8R...
```

Initially I thought of a possible missing decompression step in the binary data trasfer by the http library in use. Unfortunately executing `gunzip` on the relevant data gave `gzip: <filename>.gz: not in gzip format` . That proved to be a wrong test case as what I mentioned above about the 'PK' prefix bytes meant the data was not encoded in gzip format. As a last resort I've tried decompressing using `unzip` which failed as well (`zip archive inconsistent: central directory overlaps eocd, or there is space between them`). This led me to the conclusion that I must be receiving corrupted data, hence the issue. Moreover, running the same kind of query as above and changing format to any other arbitrary format does not result in the same problem (json, csv, text etc...) 

Note: using the python sdk it behaves correctly

Looker version: 4.0
Node.js version: v18.15.0

**Comment by jkaster** [comment]
If that's a binary payload, you should download it using the streaming methods rather than the standard methods, which don't attempt to URL decode the result.

**Comment by rhighs** [comment]
Sounds good, I'll give it a try :+1:

**Comment by rhighs** [comment]
I'm back @jkaster, I tried again using the `Looker40SDKStream` which should behave as you said. Unfortunately the error persists, still getting invalid data for `result_format: 'xlsx'`...

```js
const session = ...;
const client = Looker40SDK(session)
const streamingClient = Looker40SDKStream(session)

const runQuery = async (filters, queryFormat) => {
      const lookDef = await client.look(lookId)
      if (!lookDef.ok) {
        return [null, JSON.stringify(lookDef)]
      }

      lookDef.value.query.filters = filters
      const { client_id: clientId, ...query } = lookDef.value.query

      const request = {
        result_format: queryFormat,
        body: query
      }

      const asStream = ['xlsx', 'pdf', 'png', 'jpg'].includes(queryFormat)
      if (asStream) {
        const result = await client.run_inline_query(request)
        if (!result.ok) {
          return [null, JSON.stringify(result.error || {})]
        }

        return [result.value, null]
      } else {
        const stream = await streamingClient.run_inline_query(
          stream => stream,
          request
        )
        if (stream.error) {
          return [null, JSON.stringify(stream.error || {})]
        }

        return [stream, null]
      }
    }
```

**Comment by jkaster** [comment]
Glad you got it working for you!
