### ISSUE TITLE
LookerSDKError: API 3.x requests are prohibited. Request: POST /api/3.1/login

### ISSUE THREAD

**Issue by kavanpuranik** [looker-open-source/sdk-codegen#1362]
I am running `yarn gen` and getting the following error:

```
yarn gen ts

yarn run v1.22.17
$ NODE_CONFIG_DIR=./packages/sdk-codegen-scripts/config ts-node -O '{ "module": "commonjs", "target": "es2019" }' packages/sdk-codegen-scripts/src/sdkGen.ts ts
/Users/Kavan.Puranik/workspace/sdk-codegen/packages/sdk-rtl/lib/lookerSDKError.js:26
    var error = this ? new Error(message, errorOptions, ...rest) : Error(message, errorOptions, ...rest);
                       ^
LookerSDKError: API 3.x requests are prohibited. Request: POST /api/3.1/login
    at new LookerSDKError (/Users/Kavan.Puranik/workspace/sdk-codegen/packages/sdk-rtl/lib/lookerSDKError.js:26:24)
    at sdkError (/Users/Kavan.Puranik/workspace/sdk-codegen/packages/sdk-rtl/lib/transport.js:194:14)
    at /Users/Kavan.Puranik/workspace/sdk-codegen/packages/sdk-rtl/lib/transport.js:220:13
    at Generator.next (<anonymous>)
    at asyncGeneratorStep (/Users/Kavan.Puranik/workspace/sdk-codegen/packages/sdk-rtl/lib/transport.js:21:103)
    at _next (/Users/Kavan.Puranik/workspace/sdk-codegen/packages/sdk-rtl/lib/transport.js:22:194)
    at processTicksAndRejections (node:internal/process/task_queues:96:5) {
  errors: [],
  documentation_url: 'https://cloud.google.com/looker/docs/'
}
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command
```

The Looker instance we have provisioned is at version 23.14.23 , so not clear to me why I am getting this error.

**Comment by kavanpuranik** [comment]
I had to allow 3.x requests to get the code gen to run:

<img width="720" alt="Screenshot 2023-09-06 at 5 41 07 PM" src="https://github.com/looker-open-source/sdk-codegen/assets/167608/abf0c773-e85c-4d8a-8d30-52f28df4e1a2">

**Comment by deanlooker** [comment]
Hey Kavan, can you verify that you have updated sdk-codegen to the latest release? (v23.14.1)

**Comment by deanlooker** [comment]
@kavanpuranik please note that you will need to update your code to use API 4.0 before upgrading your Looker instance to v23.18+, which will ship in October. You can find more information on this [here](https://cloud.google.com/looker/docs/api-3x-deprecation). Thanks!

**Comment by kavanpuranik** [comment]
> can you verify that you have updated sdk-codegen to the latest release? (v23.14.1)

This error was on `main` branch. 

> please note that you will need to update your code to use API 4.0 before upgrading your Looker instance to v23.18+, which will ship in October.

This is a new integration for us, so there is no thing to update in our codebase. The issue is more to do with your sdk codegen tool. It currently requires 3.x requests to be enabled. I only need 4.x support, so ideally `yarn gen ts` should have an option to specify target version.

**Comment by Axelcouty** [comment]
Hello, 
Just tried things out for Kotlin and had the ame issue.

Thanks @kavanpuranik pointing out the settings that made it to work :+1:
