### ISSUE TITLE
Python: Add async query endpoints

### ISSUE THREAD

**Issue by amysouthwood** [looker-open-source/sdk-codegen#139]
The Problem:
* Measure how long it takes for Looker to send and receive data from a database, without actually downloading those results
* The normal methods of 'run_query' or 'run_inline_query' cannot be used as those will automatically download the results (i.e. the response contains the results)

The solution:
* Use the run async query endpoint - this triggers the query process but does not return the results
* The status of the running query can then be checked using 'Get Async Query Info' - once this says 'Complete' it is possible to download the results (or not)
    * This is actually equivalent to what happens when running queries in the Looker UI
* If you want to measure how long the queries take to execute, you can continuously hit the async query info endpoint until it returns complete

**Comment by joeldodge79** [comment]
@amysouthwood I think `create_query_task()` is what you're looking for? That's the method name (also called "operation ID") for the [Run Query Async](https://docs.looker.com/reference/api-and-integration/api-reference/v3.1/query#run_query_async) API

**Comment by amysouthwood** [comment]
Sorry! I was slow in removing this. Jax pointed it out to me!
