### ISSUE TITLE
Looks are not updated if filters on custom dimensions/measures need to be replaced

### ISSUE THREAD

**Issue by johandebeurs** [looker-open-source/sdk-codegen#1395]
Using the sample code below, I am trying to replace all instances of an old field name with a new field name. 
```
look_id = 1234
find_text = 'foo.bar'
replace_text = 'bar.baz'

sdk = looker_sdk.init40()
look = sdk.look(look_id=look_id)

look.url = look.url.replace(
    find_text,
    replace_text
)

body = {
    'dynamic_fields': look.query.dynamic_fields.replace(find_text,replace_text),
    'expanded_share_url': look.query.expanded_share_url.replace(find_text,replace_text),
    'url': look.query.url.replace(find_text,replace_text)
}
look.query.update(iterable=body)

look_v2 = sdk.update_look(
    look_id=look_id,
    body=look
)
```
When investigating the content of the `look` object prior to update, the content is correctly set, however, when inspecting the content of `look_v2` after update, there is no change, despite the `updated_at` attribute changing

**Comment by drstrangelooker** [comment]
The `url` and `share_url` are read only fields. Changing them will do nothing. In this case changing the `query` does nothing as well.

What you need to do is create a new query object, get the query_id from the return of that, and then put the new query_id into the updated look.
