### ISSUE TITLE
query_task_results is no longer returning results but the QueryTask object.

### ISSUE THREAD

**Issue by ralflizard** [looker-open-source/sdk-codegen#1412]
I see that in the latest version (23.20.0 for python at least) the method query_task_results which matches to the `/query_tasks/{query_task_id}/results` endpoint was changed to return a QueryTask object instead of the result (as stated in the documentation). The QueryTask object doesn't return anything useful that would aid in getting the actual result. With the previous version 23.18.0 it does work just fine.

Looking at the commit for this version, the change was done in the looker json spec and affects all SDK's, not sure if I'm missing something from the documentation on how to get results async, or if it is in fact a bug.

**Comment by ian-thompson-king** [comment]
Hi, @jkaster any news on this, this is a big issue for us as well.

**Comment by omarabed15** [comment]
I also encountered this. Documented my test case here: https://www.googlecloudcommunity.com/gc/Developing-Applications/Looker-API-request-for-async-data-returns-empty-QueryTask/m-p/821276#M2257

**Comment by aschott-looker** [comment]
Hey folks! This should be fixed in Looker version `24.18`!
