### ISSUE TITLE
Replace request to address security vulnerabilities 

### ISSUE THREAD

**Issue by kns482** [looker-open-source/sdk-codegen#1424]
The current use of the request package is deprecated and poses security vulnerabilities. Are there any plans to replace request?

<img width="584" alt="image" src="https://github.com/looker-open-source/sdk-codegen/assets/126187330/2c37d916-818f-45ed-8a11-6a72cc256b26">

**Comment by mnahkies** [comment]
In addition to the transient dependency on the old version of `tough-cookie`, `request` itself now has https://github.com/advisories/GHSA-p8p7-x288-28g6

It would be great to see it replaced with native fetch, axios, or similar.
