### ISSUE TITLE
TypeError on cattrs >=23.2.0

### ISSUE THREAD

**Issue by teka23** [looker-open-source/sdk-codegen#1437]
There were some potentially breaking changes in cattrs == 23.2.0

https://catt.rs/en/v23.2.3/history.html#id4

Probably caused by these changes.

**Comment by jeremytchang** [comment]
Hi! We're closing this as not reproducible, as there's no error to look at, and the exact breaking changes/resulting problems are not described in this issue. 
Please feel free to re-open this issue with more details!

**Comment by teka23** [comment]
Fixed in https://github.com/looker-open-source/sdk-codegen/pull/1469
