### ISSUE TITLE
Switch to Spectral

### ISSUE THREAD

**Issue by philsturgeon** [looker-open-source/sdk-codegen#145]
Hey I'm the original author of Speccy. I'm doing the rounds letting people know they should switch to [Spectral](https://stoplight.io/spectral/). Speccy is not getting much love these days, and Spectral is like its considerably more mature and advanced replacement.

**Comment by jkaster** [comment]
Sorry I missed this until now. Thanks so much for the heads up, @philsturgeon! I'll work on that.

**Comment by philsturgeon** [comment]
No worries, enjoy!

**Comment by jkaster** [comment]
Does spectral support a ReDoc or other viewer like speccy did? Not finding that in the docs.

**Comment by philsturgeon** [comment]
Speccy added the ReDoc CLI option before ReDoc added their own. Just use [redoc cli](https://github.com/Redocly/redoc/blob/master/cli/README.md).

**Comment by jkaster** [comment]
Thanks for the quick answer. Appreciated!
