### ISSUE TITLE
`lookml_model_explore` does not work with explores on personal branch?

### ISSUE THREAD

**Issue by eric-workweek** [looker-open-source/sdk-codegen#1452]
Hello, I'm trying to use the `lookml_model_explore` method to retrieve the fields for an explore I created. The method only seems to work with explores in production and not those created in my personal branch.

When I try something like `lookml_model_explore("my_model_name", "my_explore_name")` I get a JSON error that leads to a 404 error. Using an explore from production returns an expected `LookmlModelExplore` object.

Is it not possible to access explore properties for non-production explores?

**Comment by jeremytchang** [comment]
We will need to investigate to determine if this is expected behavior.

**Comment by drstrangelooker** [comment]
In order to "see" a personal branch you need to change the API session to dev mode. https://www.googlecloudcommunity.com/gc/Technical-Tips-Tricks/How-do-I-run-API-calls-in-dev-mode/ta-p/585558

I'm going to close this. Please reopen if you still have issues.
