### ISSUE TITLE
Python SDK: SyntaxWarning/DeprecatedWarnings invalid escape sequence

### ISSUE THREAD

**Issue by Taragolis** [looker-open-source/sdk-codegen#1460]
At least latest version [`looker-sdk`](https://pypi.org/project/looker-sdk/) raise this warnings, but I guess it might affect older ones

```console
looker_sdk/error.py:102: DeprecationWarning: invalid escape sequence \.
```

Since Python 3.12 this kind of warning become [`SyntaxWarning`](https://docs.python.org/3/library/exceptions.html#SyntaxWarning), see: [gh-98401](https://github.com/python/cpython/issues/98401), which are not ignored by default as [`DeprecatedWarnings`](https://docs.python.org/3/library/exceptions.html#DeprecationWarning) it would be nice if regexp expression will wrap into the [raw strings ](https://docs.python.org/3/reference/lexical_analysis.html#escape-sequences)

**Comment by drstrangelooker** [comment]
This should be fixed in the most recent version - 24.8
