### ISSUE TITLE
python SDKError __str__ bug

### ISSUE THREAD

**Issue by syvokobylka** [looker-open-source/sdk-codegen#1479]
Attempt to represent python SDKError object as a string leads to another exception happening
```
.....
except looker_sdk.error.SDKError as ex:
    logger.error(f"Some important data and {str(ex)}")

```

> Call stack:
> 2024-07-04 11:35:58.130	
> TypeError: sequence item 0: expected str instance, ErrorDetail found
> 2024-07-04 11:35:58.130	
>     {sep.join(self.errors)}
> 2024-07-04 11:35:58.130	
>   File "/root/.pyenv/versions/3.10.5/lib/python3.10/site-packages/looker_sdk/error.py", line 85, in __str__

**Comment by jeremytchang** [comment]
Closing as fixed. https://github.com/looker-open-source/sdk-codegen/pull/1486
