### ISSUE TITLE
Why is "limit" a string for creating queries but a number for running them?

### ISSUE THREAD

**Issue by nem035** [looker-open-source/sdk-codegen#1512]
# Problem

The `limit` property is defined as a string for the `WriteQuery` type:

https://github.com/looker-open-source/sdk-codegen/blob/main/packages/sdk/src/4.0/models.ts#L13800

Which is used for creating a query:

https://github.com/looker-open-source/sdk-codegen/blob/main/packages/sdk/src/4.0/methodsInterface.ts#L6373

But `limit` is defined as a number for the `IRequestRunQuery` type:

https://github.com/looker-open-source/sdk-codegen/blob/main/packages/sdk/src/4.0/models.ts#L8583

Which is used for running a previously created query:

https://github.com/looker-open-source/sdk-codegen/blob/main/packages/sdk/src/4.0/methodsInterface.ts#L6412

# Discussion

It's confusing why one needs to pass `"3"` when creating a query but `3` when running it.

When you create and run a query at once (i.e. run it inline):

https://github.com/looker-open-source/sdk-codegen/blob/main/packages/sdk/src/4.0/methodsInterface.ts#L6479

You also need to use a number:

https://github.com/looker-open-source/sdk-codegen/blob/main/packages/sdk/src/4.0/models.ts#L8437

Also, passing in a number when creating a query just works, despite the type being a string.

```ts
const params: Partial<IWriteQuery> = {
  model: ...,
  view: ...,
  fields: [...],
  // @ts-ignore
  limit: 3 // <--- this should be a string according to types but a number works fine
};
const query = await sdk.ok(sdk.create_query(params));
const runParams: IRequestRunQuery = {
  query_id: 1,
}
const result = await sdk.ok(sdk.run_query(runParams));
```

What's going on here? Why is `limit` a string anywhere at all?

**Comment by jkaster** [comment]
According to the Looker 4.0 API specification, it is a string type. The SDK types parameters and structures based on the API specification. Changing it to a number would be a breaking change for API 4.0, so it won't be changed, even though it is confusing.

**Comment by nem035** [comment]
Sure but it IS a number sometimes, as is the case for running the query [inline](https://github.com/looker-open-source/sdk-codegen/blob/main/packages/sdk/src/4.0/models.ts#L8425).

In total, there are 38 number type limits in models.ts:

<img width="1137" alt="Screenshot 2024-10-11 at 8 05 27 PM" src="https://github.com/user-attachments/assets/d0f97b32-28a4-488f-a4a5-0c0d406df9f6">

It's not just confusing that a numerical value is declared as a string, but it's additionally confusing that it's sometimes defined as a string and sometimes as a number. 

On top of this, the API accepts both numbers and strings.

**Comment by nem035** [comment]
Gotcha. At least I now know that this bug is actually a feature :)
