### ISSUE TITLE
In Python sdk, query_task_result results in a DeserializeError

### ISSUE THREAD

**Issue by jgarst** [looker-open-source/sdk-codegen#153]
When retrieving the result of an asynchronous query with `query_task_result`, the python sdk raises a `DeserializeError: Bad data` when catters tries to structure the list that is returned into a `MutableMapping[str, str]` on [line 71 of rtl/serialize.py](https://github.com/looker-open-source/sdk-codegen/blob/a268fd28b8c50ba0042fe13a52c94b2f6b6cd269/python/looker_sdk/rtl/serialize.py#L71)

**Comment by joeldodge79** [comment]
Thanks for bringing this up. It's actually a bug with our Looker swagger/open-api spec that I'll be addressing soon. I'll regenerate the python-sdk once that fix ships and that will close this issue (note: you will NOT need to upgrade your Looker instance)

**Comment by joeldodge79** [comment]
This is fixed in Looker 7.2 which should should start rolling out Sunday (https://docs.looker.com/relnotes). We'll release an updated SDK to match the fix next week. You'll need both upgrades (looker 7.2 and the yet-to-be-released python sdk update). stay tuned...

**Comment by joeldodge79** [comment]
should be all set now.
