### ISSUE TITLE
Newwt 

### ISSUE THREAD

**Issue by Domi83s** [looker-open-source/sdk-codegen#1552]

**Comment by Domi83s** [comment]
> 

<html devsite>
<head>
  <meta name="project_path" value="/_project.yaml">
  <meta name="book_path" value="/_book.yaml">
</head>
<body>
<h1 class="page-title">One-Page Overview</h1>

{% dynamic setvar source_file "src/main/java/com/google/devtools/build/docgen/templates/starlark-overview.vm" %}
{% include "_buttons.html" %}
#foreach ($entry in $allPages.entrySet())
<h2>


  <a href="/rules/lib/${entry.key.path}">${entry.key.title}</a>


</h2>
<ul>
#foreach ($page in $entry.value)

  <li>


    <a href="/rules/lib/${entry.key.path}/${page.name}">${page.title}</a>

  </li>

#end
</ul>
#end
</body>
</html>

**Comment by Domi83s** [comment]
Newt

**Comment by drstrangelooker** [comment]
Is there an issue here? If so please document it and reopen.
