### ISSUE TITLE
Migrate away from the request module

### ISSUE THREAD

**Issue by jkaster** [looker-open-source/sdk-codegen#175]
Request is deprecated https://github.com/request/request/issues/3142

We'll need to decide on a winner and adopt it

**Comment by riclf** [comment]
Please share your insights when you do. There are about ten viable replacements +/-. I'm sure some are not choice replacements. Thanks.

**Comment by jkaster** [comment]
Thanks, I will. I definitely have some research to do, first! If you find any you favor, feel free to call them out, too.

**Comment by poman31** [comment]
With the recent series of CVEs (Cybersecurity Vulnerabilities) reported, are there any plans to tackle this issue.
Replacing Requests with something like @Cypress/Requests  should be verily easy and its basically a drop in replacement for Requests.

**Comment by jkaster** [comment]
Fixed with #1491
