### ISSUE TITLE
Please fix Pypi state

### ISSUE THREAD

**Issue by ms32035** [looker-open-source/sdk-codegen#183]
```
$ pip install --pre looker_sdk==0.1.3b8                                                                                          ✔  
ERROR: Could not find a version that satisfies the requirement looker_sdk==0.1.3b8 (from versions: 0.1.3b1, 0.1.3b2, 0.1.3b3, 0.1.3b4)
ERROR: No matching distribution found for looker_sdk==0.1.3b8
```

**Comment by josephaxisa** [comment]
@ms32035  Thanks for letting us know. I just tested this in a clean environment and oddly enough, it worked. Can you try to uninstall any other looker_sdk version that's currently installed and then running `pip install --pre looker_sdk`? If you don't specify a version it will install the latest.

**Comment by ms32035** [comment]
```
 $ pip install --no-cache-dir --pre looker_sdk                                                                                                            
Collecting looker_sdk
  Downloading looker_sdk-0.1.3b4-py3-none-any.whl (100 kB)
```

**Comment by joeldodge79** [comment]
I also can't re-pro. I wonder if pypi is/was having some caching/cdn flakiness? Is this still happening @ms32035 ?

**Comment by ms32035** [comment]
ok, tested elsewhere and the new version got installed. indeed looks like cdn/mirror issue

**Comment by JCPistell** [comment]
fwiw i'm noticing that python 3.7 installs 0.1.3b8 while python 3.8 installs 0.1.3b4

**Comment by ms32035** [comment]
Right, my issue was on 3.8. The successful install was on 3.7. But this should not matter as installation is from source, unless the annotations in setup.py are somehow considered
