### ISSUE TITLE
Python: Creating a Data Dictionary

### ISSUE THREAD

**Issue by AlexAndorra** [looker-open-source/sdk-codegen#186]
Hi,
Thanks for your nice work. This is not an issue, but I don't really know where else to ask this question. 

I'm trying to replicate [this example](https://looker.com/platform/blocks/embedded/create-a-data-dictionary) for my model, but [the only example I found is in Ruby](https://github.com/llooker/powered_by_modules/blob/master/Use%20Cases/Data%20Dictionary.md) -- would you happen to have it in python by any chance?

Thanks a lot in advance and best regards,
Alex

**Comment by joeldodge79** [comment]
our python examples live in https://github.com/looker-open-source/sdk-examples/tree/master/python

I took a look at that ruby script and did a quick and dirty conversion of that code into python, hope it helps: https://github.com/looker-open-source/sdk-examples/blob/master/python/lookml_model_explore.py

**Comment by AlexAndorra** [comment]
That's great, thanks a lot -- gonna take a look at that!
