### ISSUE TITLE
Raise FileNotFoundError instead of InitError if looker.ini file is not found

### ISSUE THREAD

**Issue by tpakeman** [looker-open-source/sdk-codegen#218]
If an invalid path is provided to a looker.ini file then the SDK attempts to use environment variables and raises the following `InitError`:

```
  File "path/to/looker_sdk/__init__.py", line 56, in init31
    raise InitError(
looker_sdk.InitError: Missing required configuration values like base_url and api_version.
``` 

However, if a looker.ini file is provided and is missing / has a typo / is not a valid path then I suggest a `FileNotFoundError` is raised instead to make it clear what has caused the problem.

**Comment by joeldodge79** [comment]
with the change I just merged (and will release next week) - if you use the default value of `"looker.ini"` and that file doesn't exist (e.g. in the same directory as your executable/entry-point) it will still not raise `FileNotFoundError` - this is to continue supporting the case where you can have a local "looker.ini" and not specify it in the init. However if you specify another filename and it does not exist then we'll raise NotFoundError

other problems with the provided INI file should be raised by the configparser and bubbled up
