### ISSUE TITLE
fix token expiration race condition

### ISSUE THREAD

**Issue by joeldodge79** [looker-open-source/sdk-codegen#223]
Our SDK RTLs check that a token is active by comparing the "expires_in" time to "now()". Even if the system time where the SDK is running is perfectly in time with the remote server, delay in the network could cause a condition where the SDK thinks the token is valid but the server does not.

@josephaxisa had a good suggestion to consider the token invalid at maybe 90% of the expires_in time.

**Comment by jkaster** [comment]
Good point. We should apply this to all existing SDK implementations before doing another.

I think even making the token invalid at 98% of the expiration time is fine, or maybe just a 15 second window.

@dthorpe thoughts?
