### ISSUE TITLE
module looker_sdk has no attribute 'init31'

### ISSUE THREAD

**Issue by miames** [looker-open-source/sdk-codegen#279]
While running the sample code, I keep getting this error:

 sdk = looker_sdk.init31()  # or init40() for v4.0 API
AttributeError: module 'looker_sdk' has no attribute 'init31'

It doesn't work when I change it to init40() either.

**Comment by joeldodge79** [comment]
@miames most likely you're on an older version of the SDK. can you try updating to the latest version?

**Comment by jkaster** [comment]
Closed due to lack of response. Reopen if needed.
