### ISSUE TITLE
Post version 0.1.3b4 Python version solving fails

### ISSUE THREAD

**Issue by benjamineverett** [looker-open-source/sdk-codegen#281]
Using pyenv and [poetry](https://python-poetry.org/).
```
(3.8.5/envs/test-looker-sdk) ➜  test-looker-sdk poetry env info

Virtualenv
Python:         3.8.5
Implementation: CPython
Path:           /Users/beneverett/.pyenv/versions/3.8.5/envs/test-looker-sdk
Valid:          True

System
Platform: darwin
OS:       posix
Python:   /Users/beneverett/.pyenv/versions/3.8.5
```

Every looker-sdk version after version 0.1.3b4 outputs the following error:

```
(3.8.5/envs/test-looker-sdk) ➜  test-looker-sdk poetry add looker-sdk==0.1.3b5

Updating dependencies
Resolving dependencies... (0.0s)

[SolverProblemError]
The current project's Python requirement (^3.8) is not compatible with some of the required packages Python requirement:
  - looker-sdk requires Python >=3.7.0, <3.8

Because test-looker-sdk depends on looker-sdk (0.1.3b5) which requires Python >=3.7.0, <3.8, version solving failed.
```

I assume this is a `looker-sdk` bug and not a `pyenv` or `poetry` bug?

**Comment by joeldodge79** [comment]
starting with [0.1.3.b10](https://pypi.org/project/looker-sdk/0.1.3b10/) we added support for 3.8 and [0.1.3.b13](https://pypi.org/project/looker-sdk/0.1.3b13/) and above has support for 3.6. so the latest (`0.1.3b15`) has `>=3.6, <3.9`

according to poetry docs `^3.8` includes `3.8` so it should be good with `0.1.3.b10` and above (of course we recommend the latest version available!). The reason it works for `0.1.3b4` is we were neglecting to add version constraints to the metadata at that point.

**Comment by jkaster** [comment]
@benjamineverett is this still an issue for you? I presume we can close this based on Joel's answer.
