### ISSUE TITLE
(Python SDK 3.1) all_running_queries raises error

### ISSUE THREAD

**Issue by mcranston18** [looker-open-source/sdk-codegen#303]
Hi, I am trying to use `get_all_running_queries` as per the documentation, but it is not working. Is there a workaround in the meantime?

https://docs.looker.com/reference/api-and-integration/api-reference/v3.1/query#get_all_running_queries

# Current behaviour

When I call `looker.all_running_queries()`, I hit the following exception:

```
{
	"created": 1598439875.6744363,
	"asctime": "2020-08-26 11:04:35,674",
	"levelname": "INFO",
	"name": "looker_sdk.rtl.requests_transport",
	"message": "GET(https://lookerdev.apps.mycompany.com:19999/api/3.1/running_queries)",
	"request_id": "abc123",
}
***looker_sdk .error .SDKError : {
	"message": "Not found",
	"documentation_url": "http://docs.looker.com/"
}
Traceback (most recent call last ):
File "/home/vagrant/.local/share/virtualenvs/myapp-123/lib/python3.7/site-packages/looker_sdk/sdk/api31/methods.py",
line 748,
in all_running_queries
transport_options =transport_options,

File "/home/vagrant/.local/share/virtualenvs/myapp-123/lib/python3.7/site-packages/looker_sdk/rtl/api_methods.py",
line 152,
in get
return self ._return (response,
structure )
File "/home/vagrant/.local/share/virtualenvs/myapp-123/lib/python3.7/site-packages/looker_sdk/rtl/api_methods.py",
line 88,
in _return
raise error .SDKError (response .value .decode (encoding =encoding ))
```

# Expected behaviour

When I call `looker. all_running_queries()`, I expect to get back a list of my running queries.

**Comment by joeldodge79** [comment]
just to clarify the sdk method is `all_running_queries()` (the endpoint is `/running_queries`).

Our API often returns a 404 when your credentials don't have sufficient authorization. This endpoint is one of those cases. In this case you need the `see_queries` permission

**Comment by mcranston18** [comment]
Ah, okay. That makes sense. If possible, it would be great to inform the caller about lack of permissions. For instance, I was trying to create a scheduled plan through the SDK without proper permissions and the SDK bubbled up that error correctly.

**Comment by joeldodge79** [comment]
I believe we’re moving in that direction but still have many endpoints
returning a 404 instead of. 403
