### ISSUE TITLE
Clarification on legacy language generation

### ISSUE THREAD

**Issue by shivanisankar** [looker-open-source/sdk-codegen#314]
`Steve Fenigstein` at `Picomes` would like more clarification on this line in the README: "Currently, only Go and C# have legacy language generation configured". 

He believed this implied that he could just run the the legacy script for Go or C# and it would work. He believed that he could only have to configure it for other languages. However, the specific line of our README he was referring to means that even though he can't use the generator he created for supported SDKs, there's still the legacy option for using the OpenApi generator.

**Comment by jkaster** [comment]
The `legacy` generation option is intended for languages not yet generated by `codegen`. However, **any** desired language supported by the OpenAPI generator can be defined using our existing pattern for legacy generators.

Both **Look#** (C#) and **GoLook** (golang) can now be generated by `codegen` and will hopefully result in a better user experience with Looker than using the `legacy` generation option.
