### ISSUE TITLE
Python sdk.render_task(task.id) Raise SDKError

### ISSUE THREAD

**Issue by yiwang** [looker-open-source/sdk-codegen#351]
lookder_sdk 0.1.3b18 and 0.1.3b17

code similar to the example used to work but failed today 

https://github.com/looker-open-source/sdk-codegen/blob/master/examples/python/download_dashboard_pdf.py#L86

at line
`poll = sdk.render_task(task.id)`

```
    raise error.SDKError(response.value.decode(encoding=encoding))
looker_sdk.error.SDKError: {"message":"Not found","documentation_url":"http://docs.looker.com/"}
```

**Comment by joeldodge79** [comment]
@yiwang does it continue to work on 0.1.3b16 ?

**Comment by joeldodge79** [comment]
also, what version of looker are you running?

**Comment by joeldodge79** [comment]
the `download_dashboard.py` script works for me against my instance using `0.1.3b18` and Looker 7.18. I'm wondering if something happened to your dashboard on your instance?

**Comment by yiwang** [comment]
@joeldodge79 
our version is Looker 7.16.26
I don't think we changed our dashboard, also from looker UI we can render PDF correctly.

**Comment by joeldodge79** [comment]
is it broken for all dashboards on your instance?

**Comment by yiwang** [comment]
No, it seems just for that one dashboard.
Tried another dashboard and I don't see this error, so this seems a problem specific to one dashboard.

**Comment by joeldodge79** [comment]
It sounds like a data issue with that particular dashboard. DCL will hopefully be able to help you resolve it. I'm going to close this issue since I don't believe it's particularly related to the Python SDK. To absolutely verify that you could re-try it using our interactive api docs explorer and you should see the same 404/Not Found there as well
