### ISSUE TITLE
.env values are placed in the wrong ApiConfig settings

### ISSUE THREAD

**Issue by bschreder** [looker-open-source/sdk-codegen#415]
https://github.com/looker-open-source/sdk-codegen/blob/master/packages/sdk-rtl/src/apiSettings.ts

line 39:
export const ApiConfigMap = (envPrefix: string): IValueSettings => {
  if (!envPrefix) return {} as IValueSettings
  return {
    base_url: `${envPrefix}_BASE_URL`,
    client_id: `${envPrefix}_VERIFY_SSL`,
    client_secret: `${envPrefix}_TIMEOUT`,
    timeout: `${envPrefix}_CLIENT_ID`,
    verify_ssl: `${envPrefix}_CLIENT_SECRET`,
  }
}

the *_VERIFY_SSL is being assigned to client_id, ....

**Comment by jkaster** [comment]
Thanks for the bug report! I missed your report, but ended up discovering it myself also and fixed it in #444
