### ISSUE TITLE
in swagger doc:  space_id should probably be folder.id

### ISSUE THREAD

**Issue by bschreder** [looker-open-source/sdk-codegen#418]
As of Aug 2019 ( https://looker.com/blog/introducing-spaces ), spaces is now called folders.   For the create_dashboard method in the swagger documentation, 'spaces_id' is a required field, I'm guessing that 'folder.id' is now required.   If so, please update the code comments to reflect this change so the swagger doc is updated.  Here are a few places I've found spaces_id documented.

Line 2456 - https://github.com/looker-open-source/sdk-codegen/blob/master/csharp/sdk/4.0/methods.cs
Line 1706 - https://github.com/looker-open-source/sdk-codegen/blob/master/kotlin/src/main/com/looker/sdk/3.1/methods.kt
Line 1704 - https://github.com/looker-open-source/sdk-codegen/blob/master/kotlin/src/main/com/looker/sdk/3.1/streams.kt
Line 2294 - https://github.com/looker-open-source/sdk-codegen/blob/master/packages/sdk/src/3.1/methods.ts
Line 2624 - https://github.com/looker-open-source/sdk-codegen/blob/master/packages/sdk/src/3.1/streams.ts
Line 3373 - Line 2294 - https://github.com/looker-open-source/sdk-codegen/blob/master/packages/sdk/src/4.0/methods.ts
Line 3834 - https://github.com/looker-open-source/sdk-codegen/blob/master/packages/sdk/src/4.0/streams.ts

Probably others as well.

**Comment by jkaster** [comment]
Thanks for the report and details! When there's a new Looker release, we regenerate the `models` and `methods` source files for each SDK based on what the API specification tells us. Currently, I'm seeing *both* `folder_id` and `space_id` being included in many endpoints so it looks like `folder_id` hasn't been completely removed from API 4.0 yet.

The source code comments (and source code) we generate is based on what the Looker API specification says, so when the Looker API spec changes, the SDK source will change.
