### ISSUE TITLE
secret_id in embedsoo endpoint param 

### ISSUE THREAD

**Issue by Shauryadhaka** [looker-open-source/sdk-codegen#419]
hey, 
The secret_id is an alphanumeric string rather than an int. [Refrence](https://community.looker.com/looker-api-77/stuck-while-trying-to-create-an-embed-url-using-python-sdk-20826).
Also, I am not able to use that function if I keep it blank as it fails during signature validation so something is wrong.

**Comment by jkaster** [comment]
Thanks for this report! I see `secret_id` has been explained in your linked reference. Closing this.
