### ISSUE TITLE
Generate PHP SDK

### ISSUE THREAD

**Issue by alexkart** [looker-open-source/sdk-codegen#442]
Is there a way to generate PHP SDK?
As it is said in the readme:

_configure the desired language in codeGenerators.ts. Currently, only Go and C# have legacy language generation configured, and we now have a prototype Look# SDK that can be used instead of the legacy C# generator._

How exactly PHP language should be configured there? Commenting out PHP section of the code in the `codeGenerators.ts.` file doesn't work.

Could someone help?

**Comment by jkaster** [comment]
please pull the latest `main`, update and use the legacy generator with:
```sh
yarn && yarn build
yarn legacy php
```
