### ISSUE TITLE
openapi-generator-cli instead of openapi-generator

### ISSUE THREAD

**Issue by alexkart** [looker-open-source/sdk-codegen#443]
I followed the steps from the readme of using the legacy generator and it doesn't work.
When executing `yarn legacy` it generates the following error:

```
yarn legacy
yarn run v1.22.5
$ ts-node -O '{ "module": "commonjs", "target": "es2019" }' packages/sdk-codegen-scripts/src/legacy.ts
processing Looker configuration ...
generating Looker API Csharp version 4.0 ...
/bin/sh: 1: openapi-generator: not found
Error: Error, Command failed: openapi-generator generate -i spec/Looker.4.0.oas.json -g csharp -o ./api/4.0/Csharp --enable-post-process-file -papiPackage=Looker -ppackageName=looker
/bin/sh: 1: openapi-generator: not found

```
I think the issue is here https://github.com/looker-open-source/sdk-codegen/blob/master/packages/sdk-codegen-scripts/src/legacyGenerator.ts#L65
As stated in the documentation https://github.com/OpenAPITools/openapi-generator-cli/blob/master/apps/generator-cli/src/README.md#update-the-command-has-been-renamed

_You need to execute openapi-generator-cli instead of openapi-generator from now on._

So, I think the usage of `openapi-generator` command should be replaced with `openapi-generator-cli`

**Comment by izzymiller** [comment]
Should be resolved by: https://github.com/looker-open-source/sdk-codegen/pull/474
