### ISSUE TITLE
npm install for 21.0.4 (typescript) missing files?

### ISSUE THREAD

**Issue by ThatsWhatIIReckon** [looker-open-source/sdk-codegen#464]
Successfully built a Typescript application last week using SDK version 21.0.1
Attempted to do the same today using version 21.0.4 but build fails. 

Comparing the *.d.ts files in the "\node_modules\@looker\sdk-rtl" folder from a 21.0.4 install vs my previous 21.0.1 install shows all the files starting with "node" exist in the 21.0.1 folder but not in the 21.0.4. 
The same is true for the "\node_modules\@looker\sdk\lib" folder. 
See attached for details.

Simplest way to reproduce. 
- Create new Typescript project. 
- npm install @looker/sdk
- Add the typescript file from the examples in this repo (https://github.com/looker-open-source/sdk-codegen/blob/master/examples/typescript/customConfigReader.ts)
- compile. 
Build fails as neither LookerNodeSDK (previously exposed in \sdk\lib\nodeSdk.d.ts) nor NodeSettings (previously exposed in \sdk-rtl\lib\nodeSettings.d.ts) types can be found. . 
![LookerSDKFiles](https://user-images.githubusercontent.com/78714447/107174952-af268600-6a1f-11eb-96e3-de9c92d0f8a3.png)

**Comment by joeldodge79** [comment]
cc @bryans99 and @jkaster

**Comment by jkaster** [comment]
Sorry, we did a poor job of documenting a refactor. Please `npm install @looker/sdk-node` instead and that should resolve it. We've split out the Node-specific code from `@looker/sdk` into its own package, which requires `@looker/sdk`

**Comment by jkaster** [comment]
We'll update the related READMEs shortly. https://www.npmjs.com/package/@looker/sdk-node is the relevant link now.

**Comment by ThatsWhatIIReckon** [comment]
Installing @looker/sdk-node has indeed resolved my issue. Thanks

**Comment by jkaster** [comment]
Thanks for confirming! We also updated the readme.
