### ISSUE TITLE
Compatibility with go modules

### ISSUE THREAD

**Issue by mkaiser323** [looker-open-source/sdk-codegen#493]
Hi, 

For compatibility with go modules, the release tag must be prefixed with `go/` due to the fact that the go repo is in that subfolder. More details on that here: https://github.com/golang/go/wiki/Modules#publishing-a-release

As it stands now, error messages such as the one below appear when I build my project:

```
module github.com/looker-open-source/sdk-codegen@latest found (v21.0.7+incompatible), but does not contain package github.com/looker-open-source/sdk-codegen/go/rtl
```

It's a quick fix, you would just need to create a new tag (with the current code) specifically for go. Do you think you can release the latest code under the tag `go/v0.0.0` ?

Also note that anything over v2.x.x will require additional changes to the directory structure as per https://github.com/golang/go/wiki/Modules#releasing-modules-v2-or-higher

Thank you

**Comment by joeldodge79** [comment]
sorry for the lag, just created https://github.com/looker-open-source/sdk-codegen/tree/go/v21.4.0, will that work for you?

**Comment by joeldodge79** [comment]
oh wait, does `go/v21.4.0` fall into the category of needing a different directory structure? in case it does i'll create `go/v0.0.1` as well

**Comment by mkaiser323** [comment]
`go/v0.0.1` is perfect. Thank you!
