### ISSUE TITLE
Cannot create User / Group Attributes with Kotlin SDK if User Attribute is not hidden

### ISSUE THREAD

**Issue by frankspeak** [looker-open-source/sdk-codegen#544]
With the Kotlin SDK, running against Looker 7.20.12, user attribute operations fail if the user attribute is not hidden.

For `create_user_attribute()` for example, this works...
>  WriteUserAttribute(name=git_password, label=Git Password, type=string, default_value=, value_is_hidden=**true**, user_can_view=true, user_can_edit=true, hidden_value_domain_whitelist=https://foobar.com/*)

… but this fails with a 422…
> WriteUserAttribute(name=git_username, label=Git Username, type=string, default_value=, value_is_hidden=**false**, user_can_view=true, user_can_edit=true, hidden_value_domain_whitelist=null)

Similiar for `set_user_attribute_group_values`, this works...   
> [UserAttributeGroupValue(can=null, id=null, group_id=4, user_attribute_id=38, value_is_hidden=**true**, rank=null, value=1.2.3.4)]

... but this fails with a 500...
> [UserAttributeGroupValue(can=null, id=null, group_id=4, user_attribute_id=28, value_is_hidden=**false**, rank=null, value=1.2.3.4)]

Testing with the API, I think the issue may be caused by the SDK always sending the `hidden_value_domain_whitelist`, even if the value is not hidden.

API Docs:
* [Create User Attribute](https://docs.looker.com/reference/api-and-integration/api-reference/v4.0/user-attribute#create_user_attribute)
* [Set User Attribute Group Values](https://docs.looker.com/reference/api-and-integration/api-reference/v4.0/user-attribute#set_user_attribute_group_values)

**Comment by jkaster** [comment]
Thanks for the report. We'll need to investigate the `422` scenario, and we also never want users to encounter `500` errors from calling our API.

**Comment by frankspeak** [comment]
After upgrading to looker 21.0.34, looks like `set_user_attribute_group_values()` now succeeds - but `create_user_attribute()` is still failing.

**Comment by jkaster** [comment]
Thanks for the update @frankspeak. I should be able to look at this more in the next few days.

**Comment by jkaster** [comment]
The `422` error is that `type` is required for creating the attribute. Looks like the API spec structure needs an update.

```
/**
 * Dynamically generated writeable type for UserAttribute removes properties:
 * can, id, is_system, is_permanent
 *
 * @property name Name of user attribute
 * @property label Human-friendly label for user attribute
 * @property type Type of user attribute ("string", "number", "datetime", "yesno", "zipcode")
 * @property default_value Default value for when no value is set on the user
 * @property value_is_hidden If true, users will not be able to view values of this attribute
 * @property user_can_view Non-admin users can see the values of their attributes and use them in filters
 * @property user_can_edit Users can change the value of this attribute for themselves
 * @property hidden_value_domain_whitelist Destinations to which a hidden attribute may be sent. Once set, cannot be edited.
 */
data class WriteUserAttribute (
    var name: String? = null,
    var label: String? = null,
    var type: String? = null,
    var default_value: String? = null,
    var value_is_hidden: Boolean? = null,
    var user_can_view: Boolean? = null,
    var user_can_edit: Boolean? = null,
    var hidden_value_domain_whitelist: String? = null
) : Serializable
```

**Comment by jkaster** [comment]
The error being obscured in the Kotlin SDK is:

```hidden_value_domain_whitelist must be a comma-separated list of urls with optional wildcards, like "https://example.com*,localhost:9932", with bare wildcards not allowed (code: invalid)```

**Comment by frankspeak** [comment]
@jkaster , not sure I understand - the problem only occurs when the value is *not* hidden - why is the `hidden_domain_whitelist` required?  Were you able to get this SDK method to work with non-hidden user attributes?

**Comment by jkaster** [comment]
Whoops, sorry I forgot to mention an important bit:

When the parameter `value_is_hidden=false` you do not have to provide the parameter and value for `hidden_value_domain_whitelist` and the call works as expected.

**Comment by frankspeak** [comment]
I'm using the SDK and  `hidden_value_domain_whitelist` is a parameter of `WriteUserAttribute`.  

I tried null, empty strings etc.  However, it looks like the SDK always sends it and that's the bug.

As in the description above, if you don't specify it in the web UI, everything works.

**Comment by jkaster** [comment]
Reopening because of the Kotlin SDK friction for null properties.

**Comment by jkaster** [comment]
@frankspeak this should definitely be fixed with #601 now. That PR should get merged today

**Comment by jkaster** [comment]
Thanks for your patience and perseverance @frankspeak. Let me know if this doesn't solve the problem for you.

**Comment by frankspeak** [comment]
Thanks @jkaster - after the fix, we appear to be in business.

**Comment by jkaster** [comment]
Thanks for the confirmation!
