### ISSUE TITLE
NodeJs: do not hardcode apiPath for NodeSession

### ISSUE THREAD

**Issue by kiba-d** [looker-open-source/sdk-codegen#574]
Is there any reason that A[PI path is hardcoded](https://github.com/looker-open-source/sdk-codegen/blob/ee6f3e8f55e300df1a75c9be89b47f067bc08dee/packages/sdk-node/src/nodeSession.ts#L45rl) and is not dependent on selected SDK version?

**Comment by jkaster** [comment]
This class is in sdk-rtl, not sdk, so the AuthSession implementation doesn't know which API version is being used for the SDK. API 4.0 is our more future-proof version and currently the login method returns the same data (and more) as the implementation for 3.1. In short, 4.0 has longer life and works fine for both 3.1 and 4.0.
