### ISSUE TITLE
Kotlin SDK: all_projects() fails with 'Cannot deserialize value of type `com.looker.sdk.GitApplicationServerHttpScheme`'

### ISSUE THREAD

**Issue by frankspeak** [looker-open-source/sdk-codegen#611]
With the latest Kotlin sources, running against Looker 21.0.34.

1. I created a blank project via the Web UI, and configured it to point to a Custom Git Repository (CodeCommit).
2. After it's created successfully, using the Kotlin SDK, I call `update_session()` to set the session and then `all_projects()` but it fails with:
```
Calling update_session(): body=WriteApiSession(workspace_id=dev)
Response: ApiSession(can={view=true, update=true}, workspace_id=dev, sudo_user_id=null)
Calling all_projects()
Response: SDKErrorResponse(value=GET /projects com.fasterxml.jackson.databind.exc.InvalidFormatException: Cannot deserialize value of type `com.looker.sdk.GitApplicationServerHttpScheme` from String "": not one of the values accepted for Enum class: [http, https]
 at [Source: (String)"[{"id":"reports","name":"reports","git_remote_url":"https://...,"git_username":"...",""[truncated 625 chars]; line: 1, column: 372] (through reference chain: java.lang.Object[][0]->com.looker.sdk.Project["git_application_server_http_scheme"]))
...
	at com.looker.rtl.APIMethods.ok(APIMethods.kt:38) ~[kotlin-sdk-4.0.0.2.jar:na]
```

This worked until recently - I just updated to get the latest fix in [544](https://github.com/looker-open-source/sdk-codegen/issues/544).

`sdk.update_project()` is now also failing with a 422 and perhaps it's the same issue.  Without being able to get projects, not clear how to debug further

**Comment by jkaster** [comment]
This looks like a bug in the API endpoint. Investigating.

**Comment by jkaster** [comment]
> This worked until recently - I just updated to get the latest fix in [544](https://github.com/looker-open-source/sdk-codegen/issues/544).

This part confuses me, because once again, the SDK only deals with what the API sends it.

**Comment by frankspeak** [comment]
Thanks for taking a look @jkaster .  

One possibility - We upgraded from Looker 7.20.12 to 21.0.34 awhile back and it may be that it existed since the upgrade but we weren't get as far as project creation due to 544.

**Comment by jkaster** [comment]
What happens when you run the Kotlin `TestMethods` test `testAllProjects` against your Looker instance? It's still working  fine for me with all three of my returned projects, which all have `git_application_server_http_scheme` still set to null. So I'm not able to reproduce this yet.

**Comment by frankspeak** [comment]
Here you go:

```
> ./gradlew -i test --tests '*testAllProjects*'
...
TestMethods > testAllProjects FAILED
    java.lang.Error: GET /projects com.fasterxml.jackson.databind.exc.InvalidFormatException: Cannot deserialize value of type `com.looker.sdk.GitApplicationServerHttpScheme` from String "": not one of the values accepted for Enum class: [http, https]
     at [Source: (String)"[{"id":"reports","name":"reports","git_remote_url":"<our_code_commit_repo>","git_username":"<my_username>,"git_production_branch_name":"master","git_username_user_attribute":null,"git_password_user_attribute":null,"git_service_name":"_other","git_application_server_http_port":null,"git_application_server_http_scheme":"","pull_request_mode":"off","validation_required":true,"git_release_mgmt_enabled":false,"allow_warnings":false,"uses_git":true,""[truncated 264 chars]; line: 1, column: 372] (through reference chain: java.lang.Object[][0]->com.looker.sdk.Project["git_application_server_http_scheme"])
        at com.looker.rtl.APIMethods.ok(APIMethods.kt:38)
        at TestMethods.testAllProjects(TestMethods.kt:442)
```

**Comment by jkaster** [comment]
Thanks for testing. That is exceedingly strange because I run these Kotlin tests on every Looker release, and from the endpoint code the only values you received should be `"http"`, `"https"`, or `null. You may be able to work around this bad payload issue listing the explicit project fields you want in the `fields` argument.

**Comment by frankspeak** [comment]
@jkaster , thank you for the suggestion - will give it a try tomorrow.

**Comment by frankspeak** [comment]
@jkaster, no luck unfortunately - same error after calling `sdk.all_projects(null)`.  

Tried a few more things this morning:

1. Stood up a fresh instance, created a single project and configured git, all via the Web UI - still see the same error.  
2. Tried different repo types (git_service_name == "_other", "github") - same.
3. Bypassed the call and tried other project APIs.  In particular, called  `updade_session("dev")`, `create_project()` and [update_project()](https://docs.looker.com/reference/api-and-integration/api-reference/v4.0/project#update_project) directly.  That is now failing as well (it had worked before) but with a 422 error.
```
Calling update_project(): project_id=reports, body=WriteProject(name=reports, git_remote_url=<my_repo>, git_username=<my_username>, git_password=<my_password>,git_production_branch_name=master, use_git_cookie_auth=null, git_username_user_attribute=null, git_password_user_attribute=null, git_service_name=_other, git_application_server_http_port=443, git_application_server_http_scheme=https,deploy_secret=<my_deploy_secret>, unset_deploy_secret=false, pull_request_mode=required, validation_required=true, git_release_mgmt_enabled=true, allow_warnings=false, dependency_status=install_none) 
Response: SDKErrorResponse(value=PATCH /projects/reports io.ktor.client.features.ClientRequestException: Client request(http://looker:19999/api/4.0/projects/reports?) invalid: 422 Unprocessable Entity) 
```

I noticed that a new parameter had been added to the the `create_project()` / `update_project()`methods -`use_git_cookie_auth`.  Could that be a factor?  I can try upgrade the looker server from 21.0.34, see if that helps too.  Beyond that, if you have any other ideas, pls lemme know.

**Comment by jkaster** [comment]
I mean specifying the fields you need explicitly, like:

```kt
val attribs = sdk.ok<Array<UserAttribute>>(sdk.all_user_attributes("id,name,label,type"))
val projects = sdk.ok<Array<Project>>(sdk.all_projects("id,name,uses_git,git_remote_url"))
```

Because `git_application_server_http_scheme` is a deserialization issue on your instance, and I don't know why.

**Comment by frankspeak** [comment]
Ah, gotcha - I'd thought null might return no fields.  That worked, I'll close this since it's unreproducible on your side.

Purely fyi:
* Saw the same issue after upgrading to 21.4.31, using a fresh project via the web UI.
* The 422 failure from `update_project()` occurred when `git_production_branch_name=master` - if null, the call succeeded.

**Comment by jkaster** [comment]
So glad you have a work-around!

FWIW I've removed that enum constraint for future Looker releases (because the spec doesn't match reality) so the Kotlin SDK will be happy when we regenerate it after the API spec is updated. It will be a nullable string instead of an enum then.

Normally, we want **more** in our spec for clarity and integrity, but only if the enum is always guaranteed to have an established value. You receiving `""` when I receive `null` in my tests still puzzles me, though. I haven't figured out the circumstance that causes it.

And, now I won't have to. 😉
