### ISSUE TITLE
run_inline_query timeout @looker/extension-sdk-react

### ISSUE THREAD

**Issue by aissaFoxtel** [looker-open-source/sdk-codegen#625]
I am using the latest extension-sdk-react version 21.4.2

run_inline_query always times out at 30 seconds regardless of the timeout attribute passed as below:

```
import { getCore40SDK } from '@looker/extension-sdk-react';
const core40SDK = getCore40SDK();
core40SDK.run_inline_query({
            result_format: 'json',
            limit: -1,
            body: {
               some_data
            }
        },
            {
                timeout: 1000000
            })
```

I am always getting the below error in the console.

Error: Timeout at client.js:169

**Comment by bryans99** [comment]
This is a timeout issue with chatty. Add `chattyTimeout` to ExtensionProvider

**Comment by aissaFoxtel** [comment]
@bryans99 this has fixed it, thanks
