### ISSUE TITLE
GO SDK runtime does not use the timeout passed in the API call

### ISSUE THREAD

**Issue by panoskoug** [looker-open-source/sdk-codegen#692]
All the API calls in the GO mapping take an argument `rtl.ApiSettings` that contains a timeout. However, when I inspect the code it looks that the argument is not consulted, instead the default/initial setting is used. The code that needs to be change is around [here](https://github.com/looker-open-source/sdk-codegen/blob/7d9a6720f676e97c0476b34b709f7a17e1b9ec49/go/rtl/auth.go#L125).

**Comment by jeremytchang** [comment]
@jkaster What do you think of us deprecating `rtl.ApiSettings` for Go SDK? It deviates from our established ways to configure an SDK, either with environment variables or `looker.ini`.

**Comment by jeremytchang** [comment]
@panoskoug There are 2 established ways for configuring the Go SDK for now. You can do it through [env variables](https://github.com/looker-open-source/sdk-codegen#environment-variable-configuration) or [looker.ini](https://github.com/looker-open-source/sdk-codegen#configuring-lookerini-or-env). 
Are you using `rtl.ApiSettings` in some way that cannot be done with the existing ways to config?

**Comment by jkaster** [comment]
The API settings argument is the "transport options" on some of the other SDKs. The TypeScript SDK is our reference pattern implementation (almost all changes and features are seen first there). In the TypeScript SDK, the `timeout` parameter in the optional `options` argument is used to override the default HTTP request timeout for a **specific** SDK method call. The Go SDK needs to implement that for design/feature parity with the other SDKs. That way SDK users can knowingly pass in a timeout override for an API call they know will timeout with the default value.

**Comment by panoskoug** [comment]
@jeremytchang my use case is calling the API from a multi threaded service serving RPCs. We need to be able to control the timeout per RPC so any global per process settings are not adequate.

**Comment by jeremytchang** [comment]
Fix here: https://github.com/looker-open-source/sdk-codegen/pull/1287
