### ISSUE TITLE
`query_task_results` method not permitting bytes type response

### ISSUE THREAD

**Issue by nsepetys** [looker-open-source/sdk-codegen#695]
**Expected**: Permit bytes type response for `query_task_results` method. We were trying to use async run to generate `.xlsx` files and ran into the assertion error for the method's response.

**Full Review**:
There are 100 other occurrences of this assertion pattern (`assert isinstance(response, str)`) in the SDK. I did not go through them as our fledgling implementation of the python SDK is pretty low-coverage and does not utilize most of the methods in these files.

**Proposed Fix:**
I am under time constraints to get work done so I have done what I see is the "minimum" required in this [draft PR](https://github.com/looker-open-source/sdk-codegen/pull/694). If significant additional work is needed to merge this then I may be delayed in responding due to current work demands. If the draft PR is sufficient or needs limited changes I will do those and whatever is required to formally request its review.

**Comment by tomislav-mikulcek** [comment]
Ran into the same issue. My workaround was to call the 2 methods inside query_task_result directly.
