### ISSUE TITLE
The golang method CreateSsoEmbedUrl doesn't work

### ISSUE THREAD

**Issue by kurokoba** [looker-open-source/sdk-codegen#700]
The golang method(v3,v4) CreateSsoEmbedUrl doesn't work(http status 400).
I guess that EmbedSsoParams struct member TargetUrl is not serialized correctly.
Looker API"create_sso_embed_url"(post /api/3.1/embed/sso_url) requires  "The complete URL of the Looker UI page to display in the embed context. " for target_url but  TargetUrl is serialized as "{"target_url":{"Scheme":"https","Opaque":"","User":null,"Host":"xxx","Path":"/dashboards-next/xxx::index",....}"(TargetUrl type is url.URL)
in the golang method.
I cannot recognize the same issue in other languages.
I can avoid the problem to change TargetUrl's type(*string) .
I want to try essential correction and create pull-request but I don't have enough knowledge about ts(and other lang).
I hope well-skilled one to solve the problem.

ref:create_sso_embed_url
https://docs.looker.com/reference/api-and-integration/api-reference/v3.1/auth#create_sso_embed_url

**Comment by joeldodge79** [comment]
@kurokoba can you start with a PR that just fixes the GO code in place? That will give us a better idea of what actually needs to change and if it turns out to be a go code generator change we can work on that separately.

**Comment by kurokoba** [comment]
Thank you for your comment. I make pullrequest(https://github.com/looker-open-source/sdk-codegen/pull/710).
although there're some alert(?),I can't check it just now(sorry,I have no time  now because of critical tasks...)

**Comment by joeldodge79** [comment]
@kurokoba thanks for the PR - I see in our latest Looker 21.8 bindings for v4 only we switched the the url type to string: https://github.com/looker-open-source/sdk-codegen/pull/705/files#diff-220fd72c15715632ea2366ad7271a8c4e86c578204627ad50ebdc82fbe31c645R972

I'll get that published later today - let me know if it works (If not and or you really need v3 fixed too let me know)

**Comment by jeremytchang** [comment]
Closing as its been fixed.
