### ISSUE TITLE
Running examples raises ModuleNotFoundError: No module named 'sdk_exceptions'

### ISSUE THREAD

**Issue by slobodan-ilic** [looker-open-source/sdk-codegen#756]
I was trying to set up the basic SDK from python and tried to follow through with the examples. The first one that I've tried, namely the `test_connection.py` can't be run, because it raises:
```
➜  looker-sdk-example python test_connection.py
Traceback (most recent call last):
  File "test_connection.py", line 6, in <module>
    import sdk_exceptions
ModuleNotFoundError: No module named 'sdk_exceptions'
```
I tried to do a search of the `sdk_exceptions` in the repository, and I can only find it in the examples code. So I'm assuming that it's a remnant of an older version, which hasn't been updated in the examples.

Could the examples please be updated with the valid code? I'll keep researching and I'm happy to open a PR once I figure out what this is about (what should be used instead of `sdk_exceptions`).

**Comment by slobodan-ilic** [comment]
Never mind, I found the definition of the `sdk_exceptions` in the `examples` folder. It's a little bit weird that it's defined there, with no prior references that one should go forward and download the entire `example` suite, or at least copy the extra files over.

**Comment by lanlooker** [comment]
Hi @slobodan-ilic, thank you for letting us know about this issue. I'll make add a note into the readme.md python examples folder to clarify this module.
