### ISSUE TITLE
Golang - Unable to use SDK v4 due to unused import of `net/url`

### ISSUE THREAD

**Issue by Jberlinsky** [looker-open-source/sdk-codegen#765]
When using `github.com/looker-open-source/sdk-codegen/go@v0.0.2-0.20210707183859-6b3895d35e13`, importing `sdk/v4` yields an error due an an unused import of `net/url`:

```
❯ make
go build -o my-looker-client
# github.com/looker-open-source/sdk-codegen/go/sdk/v4
../../../../go/pkg/mod/github.com/looker-open-source/sdk-codegen/go@v0.0.2-0.20210707183859-6b3895d35e13/sdk/v4/models.go:39:3: imported and not used: "net/url"
make: *** [build] Error 2
make  19.85s user 5.40s system 399% cpu 6.313 total
```

At a quick glance, it does not appear that `net/url` (defined in https://github.com/looker-open-source/sdk-codegen/blob/main/go/sdk/v4/models.go#L39) is used. There are two potential remediations here:

1. If `net/url` does not need to be imported, remove the import line.
2. If there is a side effect from importing `net/url` that I'm not seeing, in accordance with the Golang [spec](https://golang.org/ref/spec#Import_declarations), the import should be declared as `_ "net/url"`):

> An import declaration declares a dependency relation between the importing and imported package. It is illegal for a package to import itself, directly or indirectly, or to directly import a package without referring to any of its exported identifiers. To import a package solely for its side-effects (initialization), use the blank identifier as explicit package name: `import _ "lib/math"`

**Comment by joeldodge79** [comment]
looks like this became unused with the 21.8 release: https://github.com/looker-open-source/sdk-codegen/pull/705/files#diff-220fd72c15715632ea2366ad7271a8c4e86c578204627ad50ebdc82fbe31c645L87
