### ISSUE TITLE
All: Request methods should support a fully specified url

### ISSUE THREAD

**Issue by jkaster** [looker-open-source/sdk-codegen#81]
Our `request` methods should work for both our API/SDK calls and calls to other HTTP resources. There are 3 modes:

- straight request path passthrough when `http://` or `https://` starts the request
- api path + relative path munging when the authenticator callback is passed in, meaning it's an API call
- base url + relative path when no authenticator is used

This will allow SDK users to *also* issue HTTP requests using our handy request methods for resources that are *not* in our SDK. Great additional functionality for a trivial level of effort on our part. 

- [x] Do for Typescript
- [ ] Do for Python - update: [more work required](https://github.com/looker-open-source/sdk-codegen/pull/97#issuecomment-555046500)
- [x] Do for Swift
- [x] Do for Kotlin

**Comment by jkaster** [comment]
@joeldodge79 I believe you said our Python SDK already does this? If so, please feel free to check the box!

**Comment by joeldodge79** [comment]
here's the typescript test for this: https://github.com/looker-open-source/sdk-codegen/blob/b6852f19325ce5705518b8337df7efa08696fb5d/typescript/looker/rtl/nodeTransport.spec.ts#L38-L48

**Comment by jkaster** [comment]
Created #116 for the Python SDK. Closing this for the other SDKs. I'll avoid creating an "all sdk" issue in the future for better tracking and management, unless it applies specifically to codegen.
