### ISSUE TITLE
Android App should Gracefully Handle Extra SDK Parameters

### ISSUE THREAD

**Issue by Aatish-Molasi** [looker-open-source/sdk-codegen#825]
Currently the Android app does not handle changes to new parameters added to the SDK. We need to handle any new parameters gracefully.

Analyzing the code it seems that the deserialization of json is handled by the SDK (Transport.kt:customClient(...)).

Possible fix would be to add disable(DeserializationFeature.FAIL_ON_IGNORED_PROPERTIES) to JacksonSerializer while setting up the serializer.
```
install(JsonFeature) {
    serializer = JacksonSerializer() {
        disable(DeserializationFeature.FAIL_ON_IGNORED_PROPERTIES)
    }
}
```

**Comment by mistryrakesh** [comment]
I have investigated further into this and setting `DeserializationFeature.FAIL_ON_IGNORED_PROPERTIES` doesn't seem to resolve this.

Using Gson as `JsonFeature` does seem to help:
```kotlin
install(JsonFeature) {
    serializer = GsonSerializer()
}
```

Though this introduces some complications which I am still trying to figure out. Once I resolve those I will create a PR for this.
