### ISSUE TITLE
Go GitDeployKey and CreateGitDeployKey do not return a deploy key

### ISSUE THREAD

**Issue by lukas-at-harren** [looker-open-source/sdk-codegen#911]
Somehow the response is always assumed to be JSON, and somehow the calls to `GitDeployKey` and `CreateGitDeployKey` always return an empty string `""`.

See https://github.com/looker-open-source/sdk-codegen/blob/main/go/rtl/auth.go#L142

This needs to be fixed, because otherwise the go client cannot create or read git deploy keys.

#### err is not checked

When I properly check and return `err`, I get `invalid character 's' looking for beginning of value` when calling `GitDeployKey`.

```diff
diff --git a/go/rtl/auth.go b/go/rtl/auth.go
index 836d4aca..46a26b73 100644
--- a/go/rtl/auth.go
+++ b/go/rtl/auth.go
@@ -133,14 +134,19 @@ func (s *AuthSession) Do(result interface{}, method, ver, path string, reqPars m
                return err
        }
        defer res.Body.Close()

        if res.StatusCode < 200 || res.StatusCode > 226 {
                return fmt.Errorf("response error: %s", res.Status)
        }

        err = json.NewDecoder(res.Body).Decode(&result)
-
+       if err != nil {
+               return err
+       }
        return nil
 }

```

**Comment by jeremytchang** [comment]
Hey thanks for finding this and bringing it up! The Go SDK definitely has a few kinks to work out and I'm working on making it better supported and have feature parity with our Looker supported SDKs. 

I've put up a PR https://github.com/looker-open-source/sdk-codegen/pull/1021 that broadly fixes this for all result types `string` `interface{}` and `struct`. Also I've commented on your PR. I've confirmed my PR fixes `GitDeployKey` and other methods that returns `string` type.

Can you please confirm my PR fixes your issues?

**Comment by jeremytchang** [comment]
Closing #1021 fix merged. Please reopen if the issue still exists!
