### ISSUE TITLE
looker-sdk 21.20.0 throws TypeError for python 3.9.10

### ISSUE THREAD

**Issue by rowedonalde** [looker-open-source/sdk-codegen#944]
Due to a [change](https://github.com/python/cpython/blame/v3.9.10/Lib/functools.py#L855) in Python's `functools` module that was included in the update from 3.9.9->3.9.10, `looker_sdk` breaks on import. The error seems to be through the `cattr` dependency:

```
  File "/opt/app/src/tvsapi/views.py", line 8, in <module>
    import looker_sdk
  File "/usr/local/lib/python3.9/site-packages/looker_sdk/__init__.py", line 32, in <module>
    from looker_sdk.sdk.api31 import methods, methods as methods31  # noqa:F401
  File "/usr/local/lib/python3.9/site-packages/looker_sdk/sdk/api31/methods.py", line 32, in <module>
    from . import models as mdls
  File "/usr/local/lib/python3.9/site-packages/looker_sdk/sdk/api31/models.py", line 11935, in <module>
    sr.converter31.register_structure_hook(
  File "/usr/local/lib/python3.9/site-packages/cattr/converters.py", line 186, in register_structure_hook
    self._structure_func.register_cls_list([(cl, func)])
  File "/usr/local/lib/python3.9/site-packages/cattr/multistrategy_dispatch.py", line 45, in register_cls_list
    self._single_dispatch.register(cls, handler)
  File "/usr/local/lib/python3.9/functools.py", line 855, in register
      raise TypeError(
TypeError: Invalid first argument to `register()`. ForwardRef('AccessToken') is not a class.
```

**Comment by rowedonalde** [comment]
Relevant discussion in `cattrs` from others who have experienced this outside of `looker_sdk`: https://github.com/python-attrs/cattrs/issues/206

**Comment by ps-jmorrow** [comment]
We're experiencing this issue as well and it's blocking our release via GHA.

**Comment by joeldodge79** [comment]
@ps-jmorrow @rowedonalde Can you pin python at <= 3.9.9 as a workaround till I can take a look?

**Comment by ps-jmorrow** [comment]
That worked as a workaround, thanks.

**Comment by jeremytchang** [comment]
Have you all been able to pull in latest with the PR change and confirm the issue is fixed? https://github.com/looker-open-source/sdk-codegen/pull/949

**Comment by alekseiloginov** [comment]
I just got some details from `cattrs` folks on what's need to be done for us to avoid this issue and to stop restricting the python version: https://github.com/python-attrs/cattrs/issues/206#issuecomment-1022792275

@joeldodge79 Any idea how much of an effort this might be?

**Comment by joeldodge79** [comment]
probably a few hours to check if switching to `register_structure_hook_func` will work for our cases like

```
python/looker_sdk/sdk/api40/models.py:sr.converter40.register_structure_hook(
python/looker_sdk/sdk/api40/models.py-    ForwardRef("AccessToken"),  # type: ignore
python/looker_sdk/sdk/api40/models.py-    forward_ref_structure_hook,  # type:ignore
python/looker_sdk/sdk/api40/models.py-)
```

and then another few hours to update `packages/sdk-codegen/src/python.gen.ts` and `looker_sdk.rtl.serialize.forward_ref_structure_hook`

so maybe a day or two's worth of work?
