### ISSUE TITLE
Generate __init__ methods for all input models

### ISSUE THREAD

**Issue by joeldodge79** [looker-open-source/sdk-codegen#98]
Currently only "Write" models get the generated __init__ (this allows callers to instantiate the class and get good tooltips from their editors on arguments).

However, there are models used for input that are not "Write" models (e.g. `WriteScheduledPlan(scheduled_plan_destination= [ScheduledPlanDestination(format="json_detail")])`) but will still be instantiated by sdk callers and should have good tool tips.

Note: in PyCharm we get an "unexpected arguments" tooltip error

**Comment by joeldodge79** [comment]
@jkaster - the generator logic only writes a "Write" model if there is at least one read-only field. in the python generator we key off a model being a `WriteType` as to whether we should generate a constructor: https://github.com/looker-open-source/sdk-codegen/blob/master/src/python.gen.ts#L255

To solve this issue we'll either need to find a different signal for "this model appears somewhere in a method signature" or simply generate `__init__` methods for ever model ...

**Comment by jkaster** [comment]
Seems like producing an `__init__` for every model gives us consistency and clarity, and also allows for the convenient use of the models in other scenarios SDK users may have that we haven't considered yet, like perhaps copying or moving items from one instance to another?
